# Generated by Django 4.1.7 on 2023-03-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('categorie', models.CharField(blank=True, max_length=10, null=True)),
                ('emplacement', models.CharField(blank=True, max_length=50, null=True)),
                ('prorio', models.CharField(blank=True, max_length=50, null=True)),
                ('imageproprio', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, max_length=100, null=True)),
                ('annee', models.DateField(blank=True, max_length=10, null=True)),
                ('carburant', models.CharField(blank=True, max_length=10, null=True)),
                ('kilometrage', models.PositiveIntegerField(blank=True, max_length=10, null=True)),
                ('boitevitesse', models.CharField(blank=True, max_length=10, null=True)),
                ('nbrplaces', models.PositiveIntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
