# Generated by Django 4.1.7 on 2023-03-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='service',
            field=models.CharField(choices=[('location', 'location'), ('course', 'course')], default=(('location', 'location'), ('course', 'course')), max_length=20),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='kilometrage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='nbrplaces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
