# Generated by Django 4.1.7 on 2023-03-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0002_voiture_service_alter_voiture_kilometrage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='prorio',
            new_name='proprio',
        ),
    ]
