# Generated by Django 4.1.7 on 2023-03-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0003_rename_prorio_voiture_proprio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='service',
            field=models.CharField(choices=[('location', 'location'), ('course', 'course'), ('livraison', 'livraison'), ('demenagement', 'demenagement')], default=(('location', 'location'), ('course', 'course'), ('livraison', 'livraison'), ('demenagement', 'demenagement')), max_length=20),
        ),
    ]
