# Generated by Django 4.1.7 on 2023-03-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0004_alter_voiture_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=' image'),
        ),
    ]
