# Generated by Django 4.1.7 on 2023-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0007_alter_voiture_image_alter_voiture_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='annee',
            field=models.DateField(blank=True, null=True, unique_for_year=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='marque',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
