# Generated by Django 4.1.7 on 2023-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0008_alter_voiture_annee_alter_voiture_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voiture_images'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='voiture_images'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='voiture_images'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='imageproprio',
            field=models.ImageField(blank=True, null=True, upload_to='voiture_images'),
        ),
    ]
