# Generated by Django 4.1.7 on 2023-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0015_voiture_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='user',
        ),
        migrations.AlterField(
            model_name='voiture',
            name='boitevitesse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
