# Generated by Django 4.1.7 on 2023-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0018_voiture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='cartegrise',
            field=models.FileField(blank=True, default=False, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='nom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='telephone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='annee',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
