# Generated by Django 4.1.7 on 2023-04-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0021_alter_voiture_annee_alter_voiture_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='Datereser',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='messageclient',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='nomclient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
