# Generated by Django 4.1.7 on 2023-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0027_voiture_status_alter_voiture_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Indisponible', 'Indisponible')], max_length=20),
        ),
    ]
