# Generated by Django 4.1.7 on 2023-04-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0028_alter_voiture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Indisponible', 'Indisponible')], default=(('Disponible', 'Disponible'), ('Indisponible', 'Indisponible')), max_length=20),
        ),
    ]
