# Generated by Django 4.1.7 on 2023-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0029_alter_voiture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='service',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
