# Generated by Django 4.1.7 on 2023-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpress', '0034_alter_voiture_service_alter_voiture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='service',
            field=models.CharField(blank=True, choices=[('Location', 'Location'), ('Livraision', 'Livraision'), ('Course', 'Course')], default='Course', max_length=20, null=True),
        ),
    ]
