# Generated by Django 4.1.7 on 2023-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cartegrise',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
