# Generated by Django 4.1.7 on 2023-04-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_profile_cartegrise_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
