# Generated by Django 4.1.7 on 2023-04-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_alter_profile_email_alter_profile_telephone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
